"""Initial migration

Revision ID: 3ecf9311a773
Revises: 
Create Date: 2026-10-08 20:50:17.422975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ecf9311a773'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User_Data',
    sa.Column('uid', sa.Uuid(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('firstName', sa.String(length=20), nullable=True),
    sa.Column('lastName', sa.String(length=20), nullable=True),
    sa.Column('midName', sa.String(length=20), nullable=True),
    sa.Column('completedTests', sa.Integer(), nullable=True),
    sa.Column('totalTests', sa.Integer(), nullable=True),
    sa.Column('abc_test_result', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user_auth.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('username')
    )
    op.drop_constraint('username', 'user_auth', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('username', 'user_auth', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_table('User_Data')
    # ### end Alembic commands ###
