"""empty message

Revision ID: 81a160f35b1d
Revises: f0470dd6bc9e
Create Date: 2026-10-08 20:58:15.863942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81a160f35b1d'
down_revision: Union[str, None] = 'f0470dd6bc9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User_info',
    sa.Column('uid', sa.Uuid(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('firstName', sa.String(length=20), nullable=True),
    sa.Column('lastName', sa.String(length=20), nullable=True),
    sa.Column('midName', sa.String(length=20), nullable=True),
    sa.Column('completedTests', sa.Integer(), nullable=True),
    sa.Column('totalTests', sa.Integer(), nullable=True),
    sa.Column('abc_test_result', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user_auth.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User_info')
    # ### end Alembic commands ###
