"""empty message

Revision ID: d82dc19a34cf
Revises: 81a160f35b1d
Create Date: 2026-10-09 18:01:42.661422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd82dc19a34cf'
down_revision: Union[str, None] = '81a160f35b1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_auth', sa.Column('role', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_auth', 'role')
    # ### end Alembic commands ###
